### ISSUE TITLE
Question about arraylist

### ISSUE THREAD

**Issue by fakecowboy** [emirpasic/gods#115]
Hi.

I have a question about arraylist. [Here](https://github.com/emirpasic/gods/blob/master/lists/arraylist/arraylist.go#L26). 

In go, the slice is already a dynamic array. Is it more appropriate to change it to an array?

**Comment by emirpasic** [comment]
@fakecowboy I think you might have a point. I can't remember my reasoning why I used a slice when I intended to use an array.

**Comment by emirpasic** [comment]
@fakecowboy took some time to get back to this question, but the reasoning is that the size of an array in golang is fixed at compiler runtime and can not be dynamically extended. Essentially then ArrayList indeed works in similar fashion to how the native slices work, however the added functionality of ArrayList could be a reason for using GoDS ArrayList rather than slice, e.g. iterators, enumerables, and other list functions.
