### ISSUE TITLE
The LinkedHashMap's Remove is O(n) ?

### ISSUE THREAD

**Issue by wxiaoguang** [emirpasic/gods#120]
The LinkedHashMap's `Remove` is O(n) ?

```
// Remove removes the element from the map by key.
// Key should adhere to the comparator's type assertion, otherwise method panics.
func (m *Map) Remove(key interface{}) {
	if _, contains := m.table[key]; contains {
		delete(m.table, key)
		index := m.ordering.IndexOf(key)   // FIXME: O(n) here ?
		m.ordering.Remove(index)
	}
}
```

**Comment by emirpasic** [comment]
Indeed, you are right. I should note that in documentation perhaps to be clear on that.

As the name suggests, the underlying structure to hold keys is a linked list in order to have the keys in the insertion order. Somebody requested this, so I've implemented it.

One could, however, implement a reversed lookup for this to find the index with O(1), but that would add more memory usage to the structure. If you feel like that's a good compromise in terms of performance vs memory, that I could change that or you can feel three to change it.
