### ISSUE TITLE
RedBlackTree runtime error: index out of range in .Values() func

### ISSUE THREAD

**Issue by shojaeix** [emirpasic/gods#174]
Hi

I am using the RedBlackTree. Sometimes, when the application is under heavy traffic, this error shows up:

```
panic: runtime error: index out of range [2477] with length 2477

goroutine 83 [running]:
github.com/emirpasic/gods/trees/redblacktree.(*Tree).Values(0xc000004210, 0x2030099, 0x2030099, 0x20)
        C:/Users/Nitro-5/go/pkg/mod/github.com/emirpasic/gods@v1.12.0/trees/redblacktree/redblacktree.go:173 +0x10f
```

First, I thought maybe it's not thread-safe, So I started to use an RWmutex for the tree, but still facing the error.

Thanks for your help 🙏🏻

**Comment by emirpasic** [comment]
@shojaeix 

GoDS is not thread-safe (seeing this, I am now having second thoughts), so protecting access to it is crucial with mutexes as you have done, otherwise, we could run into an undefined state.

The error occurs in the Values() function, so I guess that the tree is in an inconsistent state due to concurrent reads and writes. **Try using a common mutex for both reading and writing on the tree, even when calling the Values()** as something might be concurrently writing/deleting to the tree and the size of the tree in this function is not correct at that moment.


Let me know if this helps
