### ISSUE TITLE
hashbidimaps Values() returns keys

### ISSUE THREAD

**Issue by sayden** [emirpasic/gods#212]
I was looking into this by pure coincidence https://github.com/emirpasic/gods/blob/master/maps/hashbidimap/hashbidimap.go#L87 and I was wondering if it should actually be returning `Values()` instead. Happy to open a PR in such case

**Comment by ErenDursun** [comment]
I think it should be fine the way it is, because the keys of the **inverseMap** are equal to the values of the **forwardMap**.

`
// Keys returns all keys (random order).
func (m *Map) Keys() []interface{} {
	return m.forwardMap.Keys()
}

// Values returns all values (random order).
func (m *Map) Values() []interface{} {
	return m.inverseMap.Keys()
}
`

`
// Put inserts element into the map.
func (m *Map) Put(key interface{}, value interface{}) {
	if valueByKey, ok := m.forwardMap.Get(key); ok {
		m.inverseMap.Remove(valueByKey)
	}
	if keyByValue, ok := m.inverseMap.Get(value); ok {
		m.forwardMap.Remove(keyByValue)
	}
	m.forwardMap.Put(key, value)
	m.inverseMap.Put(value, key)
}
`

**Comment by emirpasic** [comment]
I think returning the keys of the inverseMap are in  fact the values as @ErenDursun  pointed out
