### ISSUE TITLE
Implement json.Marshaller interface

### ISSUE THREAD

**Issue by saheljalal** [emirpasic/gods#46]
Not sure if this is possible, but it would be nice if there were a way to implement a default json marshaling implementation so that the collection data can be exported as json.

**Comment by emirpasic** [comment]
@saheljalal 

I think I had somewhere the idea of making serialization and deserialization (marshalling/unmarshalling) of these structures. My idea was to have that done in a binary form at first, but JSON could also be another option due to readability. Let me meditate on this and find some time, last few months have been crazy for me and I hardly found any free time.

What data structures are you using and would you like this feature for? What is the use case for JSON marshalling?

**Comment by saheljalal** [comment]
I just discovered this library recently and am using the hashset to store identifiers to start.  That list is just a `[]string` but working with the set API is so much easier and faster at call sites and from a performance perspective I'm sure.  On the outgoing interface as json, however, I am just marshaling my own struct to handle this for now but was wondering if it was something that could be done in a generic fashion in the data structure itself.

**Comment by emirpasic** [comment]
@saheljalal 

In most cases, the marshalling would have to be handled individually for most structures. They would share a common interface, but the logic would be custom for each. I think that would be a cool feature and will try to include it in this lib, once I clean up the other pull requests.

From the performance perspective, there is a penalty in this lib, because it uses `interface{}` types everywhere, which gets [hit hard type assertion implementation in Go](http://stackoverflow.com/a/28027945).  I am not criticizing this lib, but one should be aware of that fact when using this lib and it's mainly due to the lack of generics (won't go there, I'll let others be opinionated on this) and, thus, having to type assert everywhere. My suggestion is to use native Go's maps with concrete types if the problem you are working on is simple. The HashSet is really a simple implementation that uses Go's native map, where key is the value as to be unique in the set and the value is empty `struct{}{}`.

**Comment by saheljalal** [comment]
@emirpasic will keep that in mind going forward and hope to see this materialize in the future.  I'd like to make more use of this library given its simple and intuitive interfaces compared to go's limited type offerings.  If performance becomes an issue, will evaluate my options at that time.  Thanks.

**Comment by lucaszanella** [comment]
I was about to ask for something like unmarshaling, it'd be very very useful

**Comment by emirpasic** [comment]
@lucaszanella sure, marshaling (serialization) and unmarshaling (deserialization) will be implemented together

**Comment by emirpasic** [comment]
@saheljalal @lucaszanella JSON [marshalling ](https://github.com/emirpasic/gods#jsonserializer) and [unmarshalling](https://github.com/emirpasic/gods#jsondeserializer) has been implemented in #53 for all data structures.

Please make note of the ```ToJSON``` and ```FromJSON``` functions from the [examples ](https://github.com/emirpasic/gods/blob/master/examples/serialization.go) and let me know if this works out for you.

**Comment by emirpasic** [comment]
closed by #53
