### ISSUE TITLE
How to find keys with given prefix in treemap by a  high efficiency way ?

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [emirpasic/gods#67]
How to find keys with given prefix in a  high efficiency way ?

Enumerable functions like "select" "find" has always to traverse all the treemap ?

**Comment by emirpasic** [comment]
> Enumerable functions like "select" "find" has always to traverse all the treemap ?

that's correct, so that's not optimal.

it's better to find the nearest (or first) matching prefix in the tree and then traverse "left & right" in tree for as long as the prefix condition is satisfied and return those results.

that logic is not implemented in GoDS, but you do have access to all the nodes and could implement that custom functionality.
